### ISSUE TITLE
release request on kinetic

### ISSUE THREAD

**Issue by furushchev** [PR2/pr2_gripper_sensor#13]
depends on https://github.com/ros/ros_realtime/issues/12

**Comment by furushchev** [comment]
Building this package itself is now successfully finished using source packages written below:

```
- git:
    local-name: PR2/pr2_gripper_sensor
    uri: https://github.com/pr2/pr2_gripper_sensor
    version: hydro-devel
- git:
    local-name: ros/ros_realtime
    uri: https://github.com/ros/ros_realtime
    version: hydro-devel
```
